package com.zoqel.audit;

public enum AuditEventType {
    RISK_DETECTED,
    PROBABILITY_CALCULATED,
    AGENT_DECISION,
    POLICY_VALIDATED,
    POLICY_BLOCKED,
    ACTION_EXECUTED,
    OUTCOME_RECORDED,
    HUMAN_ESCALATED,
    RECOVERY_CASE_OPENED,
    RECOVERY_CASE_CLOSED
}
